### ISSUE TITLE
CSS Standardization

### ISSUE THREAD

**Issue by royragsdale** [robinsloan/spring-83#13]
General philosophy/intent question. Are boards supposed to appear "the same" across clients?

It seems as though the current spec puts the burden on the publisher to ensure this, e.g. ["The board's inline CSS may override any of those rules. It may also "reset the world"]( https://github.com/robinsloan/spring-83/blob/main/draft-20220629.md?plain=1#L169).

Alternatively this burden could be placed on the client, to ensure that it is always setting up the board with the exact same setup, i.e. the client should be doing this reset, or not setting site wide css that would need to be reset.

Personally I'd lean towards the burden being on the client to provide a clean CSS environment, and boards shold appear the same across clients (at least within the box that the publisher nominally controls). I think this provides the most robust environment, e.g. many clients, easy switching, etc. Just like the early web needed [acid tests](https://www.acidtests.org/).

I can see the advantages of leaving that up to the client as a "feature" or opportunity to "value add", but think that would likely result in boards locked in to specific clients, and a fragmented ecosystem.

Curious others thoughts.

**Aside: on the specifics which have lead to this question**
Unfortunately, it seem that even with the reset, in some cases, the host CSS appears to leak into/be inherited by the shadow dom regardless. A good example of this is the follower sentinel's default css sets the [font-size](https://github.com/robinsloan/the-oakland-follower-sentinel/blob/main/style/style.css#L163) which is inherited by the boards resulting in different sizes than on other clients.

From quick experimentation, iframes seem to avoid this issue. And with [srcdoc](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/srcdoc) you don't need to wait for delcarative shadow dom to arrive for html only.

**Disclaimer:** This is my first time experimenting with the shadow DOM, and I am only passingly familiar with CSS, so perhaps there is something I am missing or a simple solution.

Some quick screenshots that hopefully help explain the above behavior I am attempting to explain: Site/Client wide CSS being inherited by boards.

1. Follower Sentinel actual (note the font size on  "The day stretched infinite", computed to 55px (11px font-size from style.css x 5rem)
![fs_actual](https://user-images.githubusercontent.com/593382/177022505-52d30db7-9afa-46d4-b96c-8c67e3474fa1.png)

2. Custom client that also includes the Follower sentinel style sheet AND the reset (the font size remains the same despite the reset)
![client_with_fs_css](https://user-images.githubusercontent.com/593382/177022553-e23808b8-950d-4559-9ca8-5598fb2f8f76.png)

3. Custom client without any CSS (large font! 5rem computes to 80px on the default firefox stylesheet)
![client_without_fs_css](https://user-images.githubusercontent.com/593382/177022560-ec12a281-6ab6-4f50-aa2f-50b6976b92b1.png)

**Comment by royragsdale** [comment]
Ah, I didn't realize that `:host` was specific to the shadow host of the shadow DOM, that would make a split Shadow DOM/iframe universe even less consistent and more fragmented.

**Comment by robinsloan** [comment]
First, a bit of sleuthing: the culprit for `all: initial` failing to reset the `font-size`, etc., has to do with my use of `rem` rather than `em` in the standard prepended board CSS. The `rem` unit references the `font-size` set on the document's HTML element -- so it re-introduces a rough kind of "inheritance".

Therefore, the `all: initial` rule dutifully severs the style connection to the enclosing document… and then properties like `font-size: 1.5rem` reach back and re-establish it! Oops.

That wasn't a considered choice -- I reflexively reach for `rem` rather than `em`, because in general web design it's almost always what you want to use -- but/and I think, in this case, `em` is the better fit. So I'll make that change, pending some testing.

<hr/>

More broadly: I am actually surprised those boards look as similar as they do. Pretty good!

The CSS styles that "leak through" the Shadow DOM are the ones [classified as "inheritable"](https://lamplightdev.com/blog/2019/03/26/why-is-my-web-component-inheriting-styles/). The suite of `font-size`, `line-height`, `color`, etc. are the ones that matter most in this context; as you indicate, without the `all: initial` reset, the client's default typography will also be the default font style for the boards.

I personally think that's okay, because of course it's true for web pages, too! Nothing wrong with a simple, text-only board being displayed with a different font in different browsers. A publisher can, if they like, fully specify their own typography, just as they can in a web page.

Perhaps the specification could provide some basic guidance to clients; something like: "1em ought to evaluate to a normal, readable body text size."

**Comment by royragsdale** [comment]
Thank you for the sleuthing, very informative. This broad point helps, "a publisher can, if they like, fully specify their own typography".

My pitfall was being unsure of what I was unknowingly "free-loading" off a specific client vs what I would expect to vary between clients, and thus require explicit specification.  That's on me to learn though, can't hold a spec accountable for a personal lack of knowledge on the underlying tools.
