### ISSUE TITLE
20220629 draft discussion

### ISSUE THREAD

**Issue by robinsloan** [robinsloan/spring-83#9]
I welcome your thoughts 😅

For my part, I feel like it is too complicated. Maybe it's exactly as complicated as it needs to be... but, if you identify anything that seems superfluous, anything that can be left "helpfully unspecified", please do suggest it. [RFC 865](https://datatracker.ietf.org/doc/html/rfc865.html) is the still the dream…

On the other hand, the difficulty factor stuff has all fallen by the wayside -- so that lightens the load.

No rush here. Take a look, let it simmer, let me know what you think.

**Comment by makeworld-the-better-one** [comment]
Thanks publishing, it's exciting stuff! I've made some step-by-step comments below, hope it's helpful. (Also, the link on the README to the current and previous draft are out of the date now)

---

> _board_: a fragment of HTML, not necessarily a valid HTML5 document

Why not necessarily a valid HTML5 document? IMO it's nice to restrict to HTML5 only, and have servers validate that.  This cuts down on misuse of the network from people who submit garbage to use the servers as a storage system.

> The server must maintain a persistent store of boards and enforce a TTL, which must be longer than three days and shorter than 22 days.

Having a variable TTL within a realm is not a great idea, because clients will get errors when requesting a board from a random server, despite that board being available somewhere. It also means that authors cannot guarantee how long they can wait before needing to update their board again -- and a minimum of three days is very short. This should either be mandated by protocol of in the realm file, and joining the realm should be an agreement to honour the TTL.

> The server must provide a valid HTML page at its base URL containing, at minimum:
> [...]
> - an articulation of its publishing standards

I would appreciate clarification on what this means. Is it a content/moderation policy? Is the onus of that on the server admins, or it should be on the realm admin, and by extension the community at-large? I vote for the latter.

> The "real" timestamp -- the one that will be verified cryptographically

There is only one timestamp so this section reads a bit confusingly.

> ISO 8601

This standard has a lot of variation and is not freely available. [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339) is a better choice, it's a subset of ISO 8601. This is a nitpick to be sure, but the nerd in me can't let it go :)

The spec doesn't seem to mention `<time>` needing to the be the very first tag. I know this was mentioned before at one point, is that not going into the final document? Because otherwise servers will need to parse the HTML, which is fine, but it's more difficult than it needs to be, and also doesn't really jive with the initial idea that boards don't need to be valid HTML5.

> Here is an example `realm.json` document:

The example JSON is not valid as the keys are not quoted.

> If the server participates in a realm, it must retrieve the JSON document describing that realm and cache it, updating it at most once per day and at least once per week.

I don't see the point in having this lower bound. Obviously servers shouldn't hammer the website, but requesting more often should be fine. Maybe it just makes sense to have one update time, no need of a bound? Such as "updating it at least every 24 hours" or something. Another consideration is recommending that servers don't update exactly on the hour/day/second/etc, but add a bit of randomness, so that the realm server doesn't get too many requests all at once.

> New boards should be transmitted to peers asynchronously. The server should wait between one and five minutes before sharing.

The range feels unnecessary and confusing for implementers. Maybe best to just stick with one time like five minutes, since this is a "should" anyway.

> In this way, the server acts as a buffer, absorbing and "compacting" rapid PUTs.

As I understand it, the server is still forwarding each PUT as a separate HTTP request. I guess the advantage is that the TCP connection can be kept open and reused, as modern HTTP libs do, but that doesn't seem like a huge win, when there is a disadvantage on the developer side of having to create a task queue and keep boards in the memory, etc.

> `Via: <server hostname, as listed in JSON document>`

This is an invalid `Via` header. [MDN says](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Via) the version of the protocol is required. So instead it should be something like
```
Via: 83 <hostname>
```
Personally I would recommend including the optional protocol name, making the header something like
```
Via: Spring/83 <hostname>
```

The `Via` header supports multiple values like most HTTP headers, so you could theory specify that servers must just add on to the existing header. This would greatly increase the consistency of the network, because servers would only fanout to servers that had never seen the PUT before, taking into account the history of the update and where it had been. The bandwidth increase would be pretty small, even in larger networks.

Here's an example header with multiple servers:
```
Via: Spring/83 example.com, Spring/83 bogbody.biz
```

> If the `Via` header is included, the server should not gossip the board back to the peer indicated.

Presumably it should randomly pick a different peer to fanout to? The other option would be to fanout to one less peer instead.

> If a peer is unreachable, or responds with an error code, the server must wait for a minimum timeout of 5 minutes before attempting to contact that peer again. If the peer is still not reachable, the server must apply a jittered backoff strategy. The server should cap its timeout at some maximum; one hour is recommended.

This seems much more complex than "try a different peer", which seems like a viable strategy to me. Other peers in the network will end up trying this server again.

> The server may operate without a realm: accepting PUT requests, storing boards, and responding to GET requests. Operating without a realm, the server may require publishers to provide additional authorization; for example, the server might be operated for members of a particular organization, who authorize themselves with organization-specific credentials. These publishers will always have to identify themselves with full board URLs, rather than bare keys.

I don't see the point of this, and supporting two different kinds of keys is annoying for client developers and hard for users to understand. If servers want to do special kinds of things they could just create their own realm. "Multi-realm" clients could be designed so that this is no issue.

Overall for this gossip section I think it would be helpful to emphasize more that servers only gossip new boards, and silently ignore boards that don't verify, are too old, are on the denylist, etc.

> The realm denylist is a plain text file.

It'd be nice if it was JSON to match the realm file, but I understand the value of having comments here.

> The server may also honor other denylists obtained from other sources. Outside the realm denylist, peers don't have to agree completely on which keys to deny; if a majority of servers in a realm deny a key, its boards will not propagate through the gossip algorithm.

I feel like this kind of ruins the point of the realm, and could cripple the network. Clients make a request to a random board in the realm, but if this server has chosen to block the key, the client just won't get it, and it won't know why. I think it's much more preferable to have all the servers obey on single denylist, and their agreement to follow only that list is why they're part of the realm. If they don't obey it, they'll be kicked out, and if they don't like the list they can either try to change it through some community process (pull request, etc.) or leave the realm. This makes the community much more united, and stops the network and user experience from breaking.

> [client] must make its request to one or more random servers in the realm

It would be good to specify client behaviour here. What should happen if the server requested returns an error? What if it returns a 404? How many requests are allowed beyond the first one? Etc.

---

Additionally:

- Where does the 22 day TTL come from, what is the rationale for that number?
- Server behaviour if the realm or denylist URL redirects is not defined
- Also, should servers gossip deletion requests? Seems like it would be useful, otherwise someone trying to remove their board would have to make a request to every server in the realm

**Comment by robinsloan** [comment]
@makeworld-the-better-one These notes are super helpful -- thank you! Great questions and suggestions.

The added complexity of the realm material in the main spec was too much for me, particularly as I thought of a first-time reader, trying to understand what's happening here.

I've therefore separated it out into the first [Spring Memo](https://github.com/robinsloan/spring-83/blob/main/memo-realms.md), modeling a format I hope can work something like Bitcoin Improvement Proposals, XMPP Extension Protocols, or (of course) RFCs. The idea is that anyone can write one!

**Comment by makeworld-the-better-one** [comment]
Glad to hear it.

I think memos might benefit from being numbered, similar to other "improvement proposals".

Personally I still lean towards mandating realms as part of the original protocol. I like the idea of just giving a client a realm URL, not any servers, and only giving it bare keys to follow. Feels simpler and cleaner than having to deal with two different kinds of keys, and knowing whether to push to servers or realms and pull from one or the other, etc. It feels like a lot on the user's mental model of how things work, and putting too much on the user is a recipe for them just finding a simple shortcut (and having a lot of errors along the way). I worry that simple shortcut will be some form of centralization, so it's nice in the protocol to just keep things simple and prevent the user from going the wrong way, so to speak.

**Comment by scren** [comment]
> Personally I still lean towards mandating realms as part of the original protocol. I like the idea of just giving a client a realm URL, not any servers, and only giving it bare keys to follow. 

Thanks! Since I read the first version of the protocol, I was challenged to understand, why a public realm file was useful. Finally I got it, realising that it not only is relevant for servers in the realm, but for clients to get a list of servers to (potentially randomly) get from and put to. Basically, a client could only remember the realm file, without any concept of a home server.

I wonder if one could add a possible place in the URL hierarchy of the Spring'83 server for the realm file, mainly to enable the realm file to be published by the same http server and on the same domain as the Spring'83 server itself. Something like `foo.bar/realm` for a server which publishes boards at `foo.bar/<key>`.
